# Einführung

Diese Fortbildung beruht auf dem fortbildungsdidaktischen Ansatz und den Materialien der Fort- und Weiterbildungsreihe „Deutsch Lehren Lernen“ (DLL) des Goethe-Instituts.

Der Kurs enthält folgende sechs Einheiten:

- DLL 2 – Wie lernt man die Fremdsprache Deutsch?

- DLL 3 – Deutsch als fremde Sprache

- DLL 6 - Curriculare Vorgaben und Unterrichtsplanung

- DLL 4 – Aufgaben, Übungen, Interaktion

- DLL 5 – Lehr- und Lernmedien

- DLL 1 - Lehrkompetenz und Unterrichtsgestaltung


Diese sechs Einheiten beschäftigen sich mit den Lehrenden als Hauptakteuren von Unterricht und den grundlegenden Elementen von Unterricht: den Lernenden, der deutschen Sprache als fremder Sprache, der Interaktion im Klassenzimmer, den Lernmaterialien und Medien sowie mit der Unterrichtsplanung und den Vorgaben für Unterricht wie Curricula und didaktisch-methodischen Prinzipien für die Unterrichtsgestaltung. In jeder der sechs Einheiten werden zunächst die grundlegenden Bedingungen des Lehrens und Lernens dargestellt, um besser zu verstehen, was das Lehren und Lernen einer Fremdsprache ausmacht. Anschließend wird erarbeitet, wie Lehrende in der Unterrichtspraxis mit diesen Erkenntnissen arbeiten können.